[tox]
requires = tox>=4
env_list = py310, py311, py312, py313, ruff

[gh-actions]
python =
    3.10: py310, ruff
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
description = run the unit tests
extras = testing
commands =
    pytest --basetemp={envtmpdir} {posargs}

[testenv:ruff]
description = lint the code base with ruff
skip_install = true
deps = ruff>=0.5
commands = ruff check src/HawkesPyLib tests
